server:
  port: 4040
  
spring:
  application:
    name: user-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
     
management:
  endpoints:
    web:
      exposure:
        include: "*"  